platforms:
  android:
    appName: Aurorapp
    packageName: io.aurora.start
    versionName: 1.0.1
    versionCode: 2005
    incrementVersionCode: true
    manifest:
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <!-- Added with Trapeze! -->
          <!-- https://capacitorjs.com/docs/apis/geolocation -->
          <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-feature android:name="android.hardware.location.gps" />
    res:
      - path: values
        file: styles.xml
        source: ./src/styles.xml
    gradle:
      - file: app/build.gradle
        target:
          android:
            buildTypes:
              release:
                minifyEnabled:
        replace:
          minifyEnabled: true
      - file: app/build.gradle
        target:
          android:
            buildTypes:
              release:
                ndk:
                  debugSymbolLevel:
        replace:
          debugSymbolLevel: "'SYMBOL_TABLE'"
      #      - file: app/build.gradle
      #        target:
      #          android:
      #            buildTypes:
      #              release:
      #        insertType: 'ndk'
      #        insert:
      #          - debugSymbolLevel: 'SYMBOL_TABLE'
      - file: variables.gradle
        target:
          ext:
            targetSdkVersion:
        replace:
          targetSdkVersion: '33'
      - file: variables.gradle
        target:
          ext:
            compileSdkVersion:
        replace:
          compileSdkVersion: '33'
      - file: variables.gradle
        target:
          ext:
            minSdkVersion:
        replace:
          minSdkVersion: '22'
